### ISSUE TITLE
Test against conda-forge phantomjs, fontconfig, freetype

### ISSUE THREAD

**Issue by lgpage** [conda-forge/nbgrader-feedstock#1]
Once [PhantomJS is feedstocked](https://github.com/conda-forge/staged-recipes/pull/692), we should use it and get rid of the yum_requirements!

See https://github.com/conda-forge/nbpresent-feedstock/issues/1

**Comment by jakirkham** [comment]
Like [this]( https://github.com/conda-forge/phantomjs-feedstock ). 😉
