### ISSUE TITLE
Update token and rerender feedback

### ISSUE THREAD

**Issue by jhamrick** [conda-forge/nbgrader-feedstock#18]
I just updated this feedstock for the 0.5.3 release of nbgrader and it would be great if the mid-term fix for https://github.com/conda-forge/conda-forge.github.io/issues/426 could be applied, re the comment:

>  If you know a release will be coming out soon, please raise an issue on your feedstock with a link to this issue and ping @conda-forge/core and we will try to move your feedstock up in the midterm queue.

Ping @conda-forge/core

**Comment by ocefpaf** [comment]
All that is needed is to send a PR re-adding the recipe to staged-recipes. I'll do that in a moment and ping you there.
