### ISSUE TITLE
Get Python2.7 builds working on Windows

### ISSUE THREAD

**Issue by lgpage** [conda-forge/nbgrader-feedstock#3]
Get Python2.7 builds working on Windows (currently skipped), see https://github.com/jupyter/nbgrader/issues/599
Needs `pytest-rerunfailure` as a conda recipe

**Comment by ocefpaf** [comment]
It the tests are failing on Windows but the package seems to be working otherwise we should be OK to create a Windows package for Python 2.7.

Note that we usually do not run the `unittests` on conda-forge for non-compiled code. That is an "upstream" task.

**Comment by jhamrick** [comment]
Closed by #13
