### ISSUE TITLE
Fix CircleCI builds

### ISSUE THREAD

**Issue by lgpage** [conda-forge/nbgrader-feedstock#6]
Currently only the Python2.7 build and tests runs and succeed. Also nothing gets uploaded to conda-forge from master for Linux. For some reason it seems the tests are causing CircleCI to bomb out.

**Comment by jhamrick** [comment]
Can you post a link to the logs for one of the failed tests?

**Comment by lgpage** [comment]
You'll notice that the tests pass but only the python2.7 build is run and nothing got uploaded to conda forge once the PR was merged into master:
- https://circleci.com/gh/conda-forge/nbgrader-feedstock/2 (PR)
- https://circleci.com/gh/conda-forge/nbgrader-feedstock/3 (Merge)

I narrowed this down to being ``invoke``s fault, but how or why I have absolutely no idea.
- https://circleci.com/gh/lgpage/nbgrader-feedstock/10

here I tried just a simple ``invoke`` command:
```
invoke tests_check --group=python
```
where ``tests_check`` was
```
@task
def tests_check(ctx, group=None):
    ctx.run("py.test -x -v -m "not formgrader and not nbextensions")
```
